FROM php:8.2-fpm

# Actualizar el sistema e instalar dependencias necesarias
RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libxml2-dev \
    libicu-dev \
    libzip-dev \
    libonig-dev \
    zlib1g-dev \
    libpq-dev \
    curl \
    git \
    unzip \
    pkg-config \
    libgd-dev \
    libxpm-dev \
    libicu-dev \
    libssl-dev \
    libmcrypt-dev \
    libcurl4-openssl-dev

# Instalar las extensiones de PHP necesarias para Laravel
RUN docker-php-ext-install pdo pdo_mysql mbstring exif pcntl bcmath gd

# Copiar Composer desde la imagen oficial de Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Establecer el directorio de trabajo
WORKDIR /var/www

# Exponer el puerto 9000 (para PHP-FPM)
EXPOSE 9000

CMD ["php-fpm"]