name: Deploy Full Stack Application
run-name: ${{ github.actor }} està desplegant l'aplicació completa 🚀
on:
  push:
    branches:
      - feature_CI-CD

jobs:
  deploy-api:
    uses: ./.github/workflows/deployNode.yml
    secrets: inherit

  deploy-frontend:
    needs: deploy-api
    uses: ./.github/workflows/deployNextJs.yml
    secrets: inherit